### ISSUE TITLE
Incorporate JS Elements   

### ISSUE THREAD

**Issue by JosephToscano1** [cse110-sp24-group20/warmup-exercise#7]
Incorporate JS elements to further enhance the widget corresponding to index.html

**Comment by j2jun** [comment]
Finished configuring script.js and linked it to the HTML.
Completed:
- A placeholder for messages that corresponds to each rating.
- An animation effect when an emoticon is clicked.
- Linked index.html to script.js.

**Comment by bmrogers2022** [comment]
Complete
